function []=DsC2Spat(datalistname)
%This function is used to select DS candidate, construct spatial network
%and optimize the edges using shortest path (SP) algorithm under Radar-Doppler Coordinate
%   Usage:
%       [] = DsC2Spat('C:\Users\DELL\Desktop\DSIpro\data_list');
%
%   Inputs:
%   - datalistname: a file with 2 channels (master secondary), i.e,
%                   20170526 20170213
%                   20170526 20170219
%                   20170526 20170303
%                   20170526 20170315
%                   ...
%   - param_list:  generated by parmslist_generator 
%
%   [1] Distributed scatterer interferometry with the refinement of spatiotemporal coherence
%        Mi Jiang, Andrea Monti-Guarnieri
%        IEEE Transactions on Geoscience and Remote Sensing vol. 58, no. 6, 
%        June 2020, pp. 3977-3987
% 
%   [2] Sentinel-1 TOPS co-registration over low-coherence areas and its 
%       application to velocity estimation using the all pairs shortest path algorithm
%        Mi Jiang
%        Journal of Geodesy vol. 94 no. 10,
%        Oct.  2020, pp. 1-15
% 
% 
% 
%   This toolbox can be used only for research purposes, you should cite 
%   the aforementioned papers in any resulting publication.
%
%   Mi JIANG, Sun Yat-sen University, 


if nargin < 1
    help DsC2Spat
    return;
end


tic;

%Read parameter file
paramslistname = 'param_list';
if ~exist(paramslistname,'file')
    error('please prepare param_list file using parmslist_generator');
end
params = readDSIpro(paramslistname);

%Input
fpath   = params.pl_path;
if ~isempty(strmatch(fpath(end),filesep))
    fpath=fpath(1:end-1);
end
pcohname = 'pcoh.mat';
maskname = 'MASK.mat';
bronumname ='shp.bro';
datalist =load(datalistname);
bro_thre = params.pl_bro; %pixels
pcoh_thre= params.pl_pcoh;
dist_thre= params.apsp_dist; %m
pix_size = params.apsp_pixsize;
nlines  = params.nlines;
nwidths = params.nwidths;
az_spacing = params.az_spacing; %m
gr_spacing = params.rg_spacing/sind(params.inc); %ground spacing %m
disp('------------Parameter Info.------------');
disp(['Lines (azimuth):        ', num2str(nlines)]);
disp(['Widths (range):         ', num2str(nwidths)]);
disp(['Azimuth pixel spacing:  ', num2str(az_spacing)]);
disp(['Ground pixel spacing:   ', num2str(gr_spacing)]);
disp(['SHP number:             ', num2str(bro_thre)]);
disp(['Posteriori coherence:   ', num2str(pcoh_thre)]);
disp(['Resample size:          ', num2str(pix_size)]);
disp('--------------------------------------- ');

%Output
dscname = 'ph.mat'; %phase of distributed scatterers [n_ps, n_image];
ijname  = 'ij.mat'; %position of distributed scatterers [az rg];

%load data
%homogeneous pixels number
bronum = freadbkj(bronumname,nlines,'uint16','b');

%posteriori coherence
pcoh=load(pcohname);
pcoh=pcoh.pcoh;

%MASK
MASK = load(maskname);
MASK = MASK.MASK;

%thresholding
idx = pcoh>=pcoh_thre&bronum>=bro_thre&MASK;

%ij coordinate
[X,Y] = meshgrid(1:nwidths,1:nlines);
ij=[Y(idx),X(idx)]; %[az rg] 
ij = single(ij);
clear Y X
pcoh = pcoh(idx);

%pl phase
npages = size(datalist,1);
n_ps   = size(ij,1); 
ph     = ones(n_ps,npages,'single');
for ii=1:npages
    if datalist(ii,2)~=datalist(1,1)
        plname = [fpath,filesep,num2str(datalist(ii,1)),'_',num2str(datalist(ii,2)),'.pl'];
        tmp    = freadbkj(plname,nlines,'cpxfloat32','b');
        ph(:,ii) = tmp(idx);
    end
end
clear tmp
save(dscname,'ph'); %coherence included
save(ijname,'ij'); 
%resample to larger grid by maximzing posteriori coherence
if ~isempty(pix_size)

    rY = pix_size/az_spacing;
    rX = pix_size/gr_spacing;

    f2Y    = floor(nlines/rY);
    f2X    = floor(nwidths/rX);
    idx    = zeros(f2Y,f2X);

    startY = 1;
    for ii=1:f2Y
        startX = 1;
      for jj=1:f2X

          ix = find(ij(:,1)>=startY&ij(:,1)<ii*rY&ij(:,2)>=startX&ij(:,2)<jj*rX);
          %find DS in ix
          if ~isempty(ix)
              [~, local_idx_best_one] = max(pcoh(ix));
              idx(ii,jj) = ix(local_idx_best_one);
          end
          startX = startX+rX;

      end
      startY = startY+rY;
    end
    idx=idx(:);
    idx(idx==0)=[];
    ij = ij(idx,:);
    ph = ph(idx,:);

end

fprintf('Refine spatial netwrok using SP algorithm.\n');

%Edge set 
[xx,yy] = meshgrid(1:size(ij,1),1:size(ij,1));
xx = triu(xx,1);
yy = triu(yy,1);
edgs = [yy(yy~=0),xx(xx~=0)];
edgs = sortrows(edgs,1);
all_edgs = sqrt((ij(edgs(:,1),1)-ij(edgs(:,2),1)).^2*az_spacing^2 + ...
    (ij(edgs(:,1),2)-ij(edgs(:,2),2)).^2*gr_spacing^2);
edgs = edgs(all_edgs < dist_thre,:);

ix = ph~=0;
ph(ix) = ph(ix)./abs(ph(ix));  

%TIN
tr = delaunayTriangulation(double(ij(:,1)),double(ij(:,2)));      
tinedgs = edges(tr); %[start end]
all_tinedgs = sqrt((ij(tinedgs(:,1),1)-ij(tinedgs(:,2),1)).^2*az_spacing^2 + ...
                          (ij(tinedgs(:,1),2)-ij(tinedgs(:,2),2)).^2*gr_spacing^2);
tinedgs = tinedgs(all_tinedgs < dist_thre,:);

%As an illustration,temporal coherence is estimated only without search solution
tempcoh_tin = ph(tinedgs(:,2),:).*conj(ph(tinedgs(:,1),:));
tempcoh_tin = tempcoh_tin.';
tempcoh_tin = abs(sum(tempcoh_tin))./sum(abs(tempcoh_tin));
GTIN = graph(tinedgs(:,1),tinedgs(:,2),-10*log10(tempcoh_tin'),size(ij,1));    

%plot TIN 
figure;
p = plot(GTIN,'XData',ij(:,2),'YData',ij(:,1),'EdgeCData',tempcoh_tin','EdgeColor','flat');colormap jet
p.MarkerSize = 1;grid on;
caxis([0,1]);    
xlim([min(ij(:,2))-20,max(ij(:,2))+20]);ylim([min(ij(:,1))-20,max(ij(:,1))+20]);
title('(a) Reference network before SP');caxis([0,1]);colorbar;axis ij

%refine path of TIN edges using SP
num=1;
startpath=[];
endpath=[];
tempcoh = ph(edgs(:,2),:).*conj(ph(edgs(:,1),:));
tempcoh = tempcoh.';
tempcoh = abs(sum(tempcoh))./sum(abs(tempcoh));
G=graph(edgs(:,1),edgs(:,2),-10*log10(tempcoh')); 

for jj=1:size(tinedgs,1)
    [tmp]  = shortestpath(G,tinedgs(jj,1),tinedgs(jj,2));
    tmpend = num + length(tmp) - 2;
    startpath(num:tmpend) = tmp(1:end-1);
    endpath(num:tmpend)   = tmp(2:end);
    num = tmpend + 1;
end    

qfrom = min(startpath,endpath);
qto   = max(startpath,endpath);
ft    = [qfrom.', qto.'];
ft    = unique(ft,'rows');% remove double arcs
[~,Lia] = ismember(ft,edgs,'rows');
GSP=graph(ft(:,1),ft(:,2),-10*log10(tempcoh(Lia)),size(ij,1));

%plot SP
figure;
p = plot(GSP,'XData',ij(:,2),'YData',ij(:,1),'EdgeCData',tempcoh(Lia)','EdgeColor','flat');
colormap(jet(65));
p.MarkerSize = 1;
caxis([0,1]);
grid on;
xlim([min(ij(:,2))-20,max(ij(:,2))+20]);ylim([min(ij(:,1))-20,max(ij(:,1))+20]);
title('(b) Reference network after SP');axis ij;caxis([0,1]);colorbar;

%comparison between TIN and SP
figure;
htin = histogram(tempcoh_tin(:));
htin.Normalization = 'probability';
htin.BinWidth = 0.01;
htin.DisplayStyle='stairs';
hold on;
hapsp = histogram(tempcoh(Lia));
hapsp.Normalization = 'probability';
hapsp.BinWidth = 0.01;
hapsp.DisplayStyle='stairs';
xlim([0,1]);xlabel('Coherence');ylabel('Probability');legend('TIN','SP')
grid on

t=toc;    
disp(['DsC2Spat operation completed in ',int2str(t/60),' min(s).']);
disp('Done!');