function [] = PhaseLinking(datalistname)
%Phase linking for interferometry under single look
% 
%   Usage:
%       [] = PhaseLinking('C:\Users\DELL\Desktop\DSIpro\data_list');
%
%   Inputs:
%   - datalistname: a file with 2 channels (master secondary), i.e,
%                   20170526 20170213
%                   20170526 20170219
%                   20170526 20170303
%                   20170526 20170315
%                   ...
%   - param_list:  generated by parmslist_generator
% 
%   [1] Distributed Scatterer Interferometry with The Refinement of Spatiotemporal Coherence, 
%       Jiang Mi, Monti-Guarnieri Andrea. IEEE Transactions on Geoscience and Remote Sensing, 58(6): 3977-3987, 2020.
% 
%
% 
% 
%   This toolbox can be used only for research purposes, you should cite 
%   the aforementioned papers in any resulting publication.
%
%   Mi JIANG, Sun Yat-sen University  
%
%   ======================================================================
%   10/2018 MJ: add iw (intensity weighted coherence estimation) option
%   01/2019 MJ: add full network averaged coherence
%   04/2019 MJ: remove coh_opt and iw option
%   04/2019 MJ: fix the bug that pixels are 0 in whole stack
%   12/2020 MJ: remove SHP file and combine SHP selection and PL
%   01/2021 MJ: add single-master coherence series to *.pl files
%   ======================================================================


if nargin < 1
    help PhaseLinking
    return;
end

tic;

%Read parameter file
paramslistname = 'param_list';
if ~exist(paramslistname,'file')
    error('please prepare param_list file using parmslist_generator');
end
params = readDSIpro(paramslistname);

%Input
fpath   = params.diff_path;
if ~isempty(strmatch(fpath(end),filesep))
    fpath=fpath(1:end-1);
end
plpath  = params.pl_path;
if ~isempty(strmatch(plpath(end),filesep))
    plpath=plpath(1:end-1);
end
nlines  = params.nlines;
nwidths = params.nwidths;
CalWin  = params.shp_calwin; %[az rg]
blksize = params.pl_blksize;
shpname = 'shp.ft';
datalist= load(datalistname); 

%Output
networkcohname = 'fullnetworkcoh.mat';
pcohname = 'pcoh.mat';
maskname = 'MASK.mat';
%[plpath,filesep,*.pl]
%output folder of optimal phases
if exist(plpath,'dir')
    rmdir(plpath,'s');
end
mkdir(plpath);

%Blk processing
RadiusRow=(CalWin(1)-1)/2;
RadiusCol=(CalWin(2)-1)/2;  
widthidx = floor(linspace(1,nwidths,blksize+1));
if min(diff(widthidx)<=RadiusCol)
    blksize =1;
end
fprintf('Estimate Covariance Matrix (%d block)...\n',blksize);    
block_size=zeros(blksize,2);
for i=1:blksize
    if i~=blksize
        block_size(i,:)=[widthidx(i),widthidx(i+1)-1];
    else
        block_size(i,:)=[widthidx(i),nwidths];
    end
end
shpind(:,1) = sub2ind([nlines,nwidths], ones(blksize,1), block_size(:,1));
shpind(:,2) = sub2ind([nlines,nwidths], ones(blksize,1)*nlines, block_size(:,2)); 

npages = size(datalist,1);
ref_idx = datalist(:,2)==datalist(1,1);   %index of master image in time-series
pcoh = zeros(nlines,nwidths,'single');%posterior coherence
temp_mask = true(npages,npages);
temp_mask = triu(temp_mask,1);
fullnetworkcoh = zeros(npages,npages); %full netwrok coherence 
%Mask file
MASK = true(nlines,nwidths);

num=1;
p=1;
all = nlines*nwidths;
all_step = floor(all/10);

for ii=1:blksize
    
    temp_start = block_size(ii,1)-RadiusCol;
    temp_end   = block_size(ii,2)+RadiusCol;
    if temp_start < 1
        temp_start = 1;
    end
    if temp_end > nwidths
        temp_end = nwidths;
    end
    
    %read differential interferograms
    imgstack = ones(nlines,temp_end-temp_start+1,npages,'single');
    for jj=1:npages 
        if datalist(jj,2)~=datalist(1,1)
            diffname = [fpath,filesep,num2str(datalist(jj,1)),'_',num2str(datalist(jj,2)),'.diff'];
            imgstack(:,:,jj)   = freadbkj(diffname,nlines,'cpxfloat32','b',1,nlines,temp_start,temp_end);  %master - slave m-1, m-2, m-n_ifg 
        end       
    end  
    imgstack = conj(imgstack); %slave-master: 1-m, 2-m,...,n_ifg-m
    ix=imgstack~=0;
    imgstack(ix)=imgstack(ix)./abs(imgstack(ix)); %
    clear ix
    
    %processed width before padding edges
    local_width = block_size(ii,2) - block_size(ii,1)+1;

    %mask pixels in stack are 0 in whole time-series
    tmp = sum(imgstack,3)~=0;
    MASK(:,temp_start:temp_end)=logical(MASK(:,temp_start:temp_end).*tmp);

    %SHP footprint
    SHP = logical(freadbkj(shpname,nlines*nwidths,'uchar','b',shpind(ii,1),shpind(ii,2),1,CalWin(1)*CalWin(2)));
    
    %mask pixels with zero brothers
    tmp = reshape(sum(SHP,2),nlines,local_width);
    tmp = tmp ~= 1;
    MASK(:,block_size(ii,1):block_size(ii,2))=logical(MASK(:,block_size(ii,1):block_size(ii,2)).*tmp);
    clear tmp
    
    %Edge process, up and down first, followed by left or right
    imgstack = padarray(imgstack,[RadiusRow 0],'symmetric');
    if temp_start==1
        imgstack = padarray(imgstack,[0 RadiusCol],'symmetric','pre');
    end
    if temp_end == nwidths
        imgstack = padarray(imgstack,[0 RadiusCol],'symmetric','post');
    end
    
    %temporal variable
    num_shp = 1;
    %optimal phase
    optphase = zeros(nlines,local_width,npages,'single');
    %coherence
    coh_pl = optphase;
    
    %Phase Linking
    for jj=1:local_width
        for kk=1:nlines
            if MASK(kk,jj+block_size(ii,1)-1)
                
                x_patch = jj+RadiusCol;
                y_patch = kk+RadiusRow;   
                
                %covariance matrix estimation
                Z = imgstack(y_patch-RadiusRow:y_patch+RadiusRow,x_patch-RadiusCol:x_patch+RadiusCol,:);
                Z = reshape(Z,[CalWin(1)*CalWin(2),npages]).';
                Z = Z(:,SHP(num_shp,:));
                CpxCoh = double(Z*Z'./size(Z,2));
                
                %coherence matrix
                Coh = abs(CpxCoh);
                
                %N(N-1)/2 mean-coherence in spatial
                fullnetworkcoh = fullnetworkcoh + Coh;
                
                %single-master time-series coherence maps
                coh_pl(kk,jj,:) = Coh(:,ref_idx);
                
                %positive definite detection
                [~,r] = chol(Coh); 
                e=1e-6;
                while ~(r == 0 && rank(Coh) == npages)
                    Coh = Coh+eye(npages)*e;
                    [~,r] = chol(Coh);
                    e=2*e;
                end   
                
                %phase optimization
                [V,~]=eig(inv(Coh).*CpxCoh);
                V=V(:,1);%using eigenvector corresponding to minimum eigenvalue (1,2,..,m,...,n)
                optphase(kk,jj,:)=V/V(ref_idx);%set the reference phase as 0 (1-m,2,-m,...,0,...,n-m)
                
                %posteriori coherence
                rho = exp(1j*(angle(CpxCoh)-angle(V*V'))); 
                rho = rho(temp_mask);
                rho = sum(rho); 
                pcoh(kk,jj+block_size(ii,1)-1) = rho;
                          
            end
            num=num+1;num_shp=num_shp+1;
            if num == all_step * p
                disp(['phase linking process: ', num2str(10*p),'%']);
                p = p+1;
            end                  
        end
    end
    %output
    %pl part
    fprintf('Output estimated %d PL phases for Block: %d \n', npages,ii); 
    optphase = coh_pl.*exp(-1j*angle(optphase)); 
    for ll = 1:npages
        if blksize==1
            filename=[plpath,filesep,num2str(datalist(ll,1)),'_',num2str(datalist(ll,2)),'.pl'];
        else
            filename=[plpath,filesep,num2str(datalist(ll,1)),'_',num2str(datalist(ll,2)),'_',num2str(ii),'.pl'];
        end
        fwritebkj(optphase(:,:,ll), filename,'cpxfloat32','b');
    end

end

clear optphase imgstack

%output
%posteriori coherence
pcoh = real(pcoh)*2/npages/(npages-1); 
save(pcohname,'pcoh');
fullnetworkcoh = fullnetworkcoh/sum(MASK(:));
%N(N-1)/2 mean coherence in spatial
save(networkcohname,'fullnetworkcoh');
save(maskname,'MASK');

%Combine opt phase
if blksize~=1
    tmp = zeros(nlines,nwidths,'single');
    for ll=1:npages
        filename = [plpath,filesep,num2str(datalist(ll,1)),'_',num2str(datalist(ll,2))];
        for ii=1:blksize
            tmp(:,block_size(ii,1):block_size(ii,2))=freadbkj([filename,'_',num2str(ii),'.pl'],nlines,'cpxfloat32','b');
        end
        fwritebkj(tmp,[filename,'.pl'],'cpxfloat32','b');
        delete([filename,'*_*.pl']);
    end
end

figure;imagesc(pcoh,[0,1]);
ti=title ('Posteriori coherence');
set(ti,'fontweight','bold');colormap jet;colorbar


t=toc;    
disp(['PhaseLinking operation completed in ',int2str(t/60),' min(s).']);
disp('Done!');
      