function []=SHP_SelPoint_v2()
%This function is used to select homogeneous pixels (SHP) on SAR intensity stack
%   Usage:
%       []=SHP_SelPoint_v2()
%   Input:
%       - param_list:  generated by parmslist_generator
%
%   [1] Distributed scatterer interferometry with the refinement of spatiotemporal coherence
%        Mi Jiang, Andrea Monti-Guarnieri
%        IEEE Transactions on Geoscience and Remote Sensing vol. 58, no. 6, 
%        June 2020, pp. 3977-3987
%
%   [2] Fast Statistically Homogeneous Pixel Selection for Covariance Matrix Estimation for Multitemporal InSAR
%        Mi Jiang, Xiaoli Ding, Ramon F. Hanssen, Rakesh Malhotra and Ling Chang,
%        IEEE Transactions on Geoscience and Remote Sensing vol. 53, no. 3,
%        March 2015, pp. 1213-1224.
% 
%   [3] The potential of more accurate InSAR covariance matrix estimation for land cover mapping
%        Mi Jiang, Bin Yong, Xin Tian, Rakesh Malhotra, Rui Hu, Zhiwei Li, Zhongbo Yu and Xinxin Zhang,
%        ISPRS Journal of Photogrammetry and Remote Sensing Vol. 126,
%        April 2017, pp. 120-128.
% 
% 
%   Tip: when N-looks intensity images are used, only BWS can be used@!  
%
%
%   This toolbox can be used only for research purposes, you should cite 
%   the aforementioned papers in any resulting publication.
%
%   Mi JIANG, Sun Yat-sen University,  
%
%   ============================================================
%   11/2021 MJ change input/ouptput opinion
%   ============================================================


tic;

%Read parameter file
paramslistname = 'param_list';
if ~exist(paramslistname,'file')
    error('please prepare param_list file using parmslist_generator');
end

params = readDSIpro(paramslistname);

%input
nlines  = params.nlines;
nwidths = params.nwidths;
mlipath = params.mli_path;
CalWin  = params.shp_calwin; %[az rg]
Alpha   = params.shp_alpha;
EstAgr  = params.shp_method;
disp('------------Parameter Info.------------');
disp(['Lines (azimuth):        ', num2str(nlines)]);
disp(['Widths (range):         ', num2str(nwidths)]);
disp(['SHP algorithm:          ', EstAgr]);
disp(['Sliding window size:    ', '[',num2str(CalWin(1)),' ',num2str(CalWin(2)),']']);
disp(['Alpha:                  ', num2str(Alpha)]);		
disp('--------------------------------------- ');

%output
shpftname = 'shp.ft'; %shp footprint
broname   = 'shp.bro';%number of brother pixels

mlistack = ImgRead(mlipath,'mli',nlines,'float32'); %read intensity series with suffixname mli
mlistack = mlistack.datastack;
mlistack = single(mlistack);
[~,~,npages] = size(mlistack);

%parameter prepare:
RadiusRow=(CalWin(1)-1)/2;
RadiusCol=(CalWin(2)-1)/2;
InitRow=(CalWin(1)+1)/2; % InitRow is CenterRow
InitCol=(CalWin(2)+1)/2; % InitCol is CenterCol

%edge mirror-image
mlistack = padarray(mlistack,[RadiusRow RadiusCol],'symmetric');
meanmli = mean(mlistack,3);
[nlines_EP,nwidths_EP]= size(meanmli);
PixelInd=false(CalWin(1)*CalWin(2),nlines*nwidths);

%estimate SHPs
num=1;
p=1;
all = nlines*nwidths;
all_step = floor(all/10);

if strcmpi(EstAgr,'FaSHPS') 
    
    %Set thresholds for parameter statistics
    LRT_nl = 3;
    LRT_nw = 3;
    if RadiusRow<LRT_nl
        LRT_nl=1;
    end
    if RadiusCol<LRT_nw
        LRT_nw=1;
    end

    %Critical region
    CR_lo = finv(Alpha/2,2*npages,2*npages);
    CR_up = finv(1-Alpha/2,2*npages,2*npages);
    Galpha_L = gaminv(Alpha/2,npages,1);
    Galpha_U = gaminv(1-Alpha/2,npages,1);    
    
    for kk=InitCol:nwidths_EP-RadiusCol
        for ll=InitRow:nlines_EP-RadiusRow       
            %Initial estimation (Likelihood-ratio test)
            temp = meanmli(ll-LRT_nl:ll+LRT_nl,kk-LRT_nw:kk+LRT_nw);
            T = meanmli(ll,kk)./temp;
            T = T>CR_lo&T<CR_up;
            SeedPoint = mean(temp(T));
            %iteration (Gamma Confidence interval)
            MeanMatrix = meanmli(ll-RadiusRow:ll+RadiusRow,kk-RadiusCol:kk+RadiusCol);
            SeedPoint = MeanMatrix>Galpha_L*SeedPoint/npages&MeanMatrix<Galpha_U*SeedPoint/npages; %check membership
            SeedPoint(InitRow,InitCol)=true;
            %connection
            LL = bwlabel(SeedPoint); %double
            PixelInd(:,num)=LL(:)==LL(InitRow,InitCol);  
            num=num+1;
            if num == all_step * p
                disp(['progress: ', num2str(10*p),'%']);
                p = p+1;
            end
        end
    end
else %BWS (non-parameter statistics)
    for kk=InitCol:nwidths_EP-RadiusCol
        for ll=InitRow:nlines_EP-RadiusRow
            Matrix = mlistack(ll-RadiusRow:ll+RadiusRow,kk-RadiusCol:kk+RadiusCol,:);
            Ref = Matrix(InitRow,InitCol,:);
            T = BWStest(repmat(Ref(:),[1,CalWin(1)*CalWin(2)])...
                ,reshape(Matrix,[CalWin(1)*CalWin(2),npages])',Alpha);   
            temp=reshape(~T,[CalWin(1),CalWin(2)]);
            %connection
            LL = bwlabel(temp);
            PixelInd(:,num)=LL(:)==LL(InitRow,InitCol);       
            num=num+1;
            if num == all_step * p
                disp(['progress: ', num2str(10*p),'%']);
                p = p+1;
            end              
        end
    end   
end

%SHPs map            
BroNum = sum(PixelInd,1);
BroNum = uint16(reshape(BroNum(:),[nlines,nwidths]));    
          
%output 
if exist(shpftname,'file')
    delete(shpftname);
end
fwritebkj(PixelInd',shpftname,'uchar','b');
if exist(broname,'file')
    delete(broname);
end
fwritebkj(BroNum,broname,'uint16','b');
t=toc;

figure;imagesc(BroNum);axis image off;colormap jet;
ti=title ('Homogeneous Pixel Number');colorbar;
set(ti,'fontweight','bold');
disp(['SHP_SelPoint operation completed in ',int2str(t/60),' min(s).']);
disp('Done!');

    